export const FETCH_YESNO = "FETCH_YESNO";
export const FETCH_YESNO_SUCCESS = "FETCH_YESNO_SUCCESS";
export const FETCH_YESNO_FAIL = "FETCH_YESNO_FAIL";

export const FIBO_SET_COUNT = "FIBO_SET_COUNT";
export const FIBO_START_CALC = "FIBO_START_CALC";
export const FIBO_CALC_SUCCESS = "FIBO_CALC_SUCCESS";

export const UPLOAD_FILE = "UPLOAD_FILE";
export const UPLOAD_FILE_SUCCESS = "UPLOAD_FILE_SUCCESS";
export const UPLOAD_FILE_FAIL = "UPLOAD_FILE_FAIL";

export const FETCH_UPLOADED_FILES = "FETCH_UPLOADED_FILES";
export const FETCH_UPLOADED_FILES_SUCCESS = "FETCH_UPLOADED_FILES_SUCCESS";
export const FETCH_UPLOADED_FILES_FAIL = "FETCH_UPLOADED_FILES_FAIL";
