export const FETCH_YESNO = "FETCH_YESNO";
export const FETCH_YESNO_SUCCESS = "FETCH_YESNO_SUCCESS";
export const FETCH_YESNO_FAIL = "FETCH_YESNO_FAIL";

export const FIBO_SET_COUNT = "FIBO_SET_COUNT";
export const FIBO_START_CALC = "FIBO_START_CALC";
export const FIBO_CALC_SUCCESS = "FIBO_CALC_SUCCESS";